export type RouteGroup = 'Start' | 'Charts' | 'Finance' | 'Customize' | 'Features' | 'Reference';
/** The job a chart does, which groups the Charts section under quiet subheadings. */
export type ChartJob = 'Trends' | 'Comparison' | 'Part of a whole' | 'KPIs' | 'Patterns' | 'Cool';
export type RouteIcon =
  | 'area'
  | 'line'
  | 'bar'
  | 'ranking'
  | 'sparkline'
  | 'radial'
  | 'activity'
  | 'progress'
  | 'radar'
  | 'slope'
  | 'combo'
  | 'funnel'
  | 'sankey'
  | 'scatter'
  | 'heatmap'
  | 'treemap'
  | 'skyline'
  | 'blockcity'
  | 'ridgeline'
  | 'spiral'
  | 'chordloom'
  | 'rankribbons'
  | 'eventhelix'
  | 'contourislands'
  | 'parallelribbons'
  | 'sunburstterraces'
  | 'clusterconstellation'
  | 'ternaryprism'
  | 'windrose'
  | 'marimekkoblocks'
  | 'intersectiontowers'
  | 'horizonfolds'
  | 'circlearchipelago'
  | 'helixribbons'
  | 'voxelcloud'
  | 'arcbridges'
  | 'terrain'
  | 'hexcity'
  | 'voxel'
  | 'range'
  | 'boxplot'
  | 'candlestick'
  | 'indicator'
  | 'depth'
  | 'orderbook'
  | 'portfolio'
  | 'price'
  | 'sync'
  | 'pin'
  | 'compare'
  | 'targets'
  | 'speed'
  | 'start'
  | 'api'
  | 'motion'
  | 'background'
  | 'surface'
  | 'cube'
  | 'legend'
  | 'ruler'
  | 'hover'
  | 'numbers'
  | 'palette'
  | 'loading'
  | 'empty';

export interface AppRoute {
  id: string;
  group: RouteGroup;
  label: string;
  title: string;
  href: string;
  pathname: string;
  icon: RouteIcon;
  /** Nests this route under another in the sidebar. */
  parent?: string;
  /** For charts: the subheading it sits under. */
  job?: ChartJob;
  navigation: boolean;
  /** A short tag beside the label, such as "New" for families rebuilt as cards. */
  badge?: string;
}

export const appRoutes = [
  {
    id: 'getting-started',
    group: 'Start',
    label: 'Getting started',
    title: 'Getting started',
    href: '/guides/installation',
    pathname: '/guides/installation',
    icon: 'start',
    navigation: true,
  },
  {
    id: 'area',
    group: 'Charts',
    job: 'Trends',
    label: 'Area',
    title: 'Area chart',
    href: '/charts/area',
    pathname: '/charts/area',
    icon: 'area',
    navigation: true,
  },
  {
    id: 'line',
    group: 'Charts',
    job: 'Trends',
    label: 'Line',
    title: 'Line chart',
    href: '/charts/line',
    pathname: '/charts/line',
    icon: 'line',
    navigation: true,
  },
  {
    id: 'combo',
    group: 'Charts',
    job: 'Trends',
    label: 'Combo',
    title: 'Combo chart',
    href: '/charts/combo',
    pathname: '/charts/combo',
    icon: 'combo',
    navigation: true,
  },
  {
    id: 'bar',
    group: 'Charts',
    job: 'Comparison',
    label: 'Bar',
    title: 'Bar chart',
    href: '/charts/bar',
    pathname: '/charts/bar',
    icon: 'bar',
    navigation: true,
  },
  {
    id: 'ranking',
    group: 'Charts',
    job: 'Comparison',
    label: 'Horizontal bar',
    title: 'Horizontal bars',
    href: '/charts/horizontal-bar',
    pathname: '/charts/horizontal-bar',
    icon: 'ranking',
    navigation: true,
  },
  {
    id: 'slope',
    group: 'Charts',
    job: 'Comparison',
    label: 'Slope',
    title: 'Slope chart',
    href: '/charts/slope',
    pathname: '/charts/slope',
    icon: 'slope',
    navigation: true,
  },
  {
    id: 'range',
    group: 'Charts',
    job: 'Comparison',
    label: 'Range',
    title: 'Range chart',
    href: '/charts/range',
    pathname: '/charts/range',
    icon: 'range',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'radial',
    group: 'Charts',
    job: 'Part of a whole',
    label: 'Radial',
    title: 'Radial chart',
    href: '/charts/radial',
    pathname: '/charts/radial',
    icon: 'radial',
    navigation: true,
  },
  {
    id: 'treemap',
    group: 'Charts',
    job: 'Part of a whole',
    label: 'Treemap',
    title: 'Treemap',
    href: '/charts/treemap',
    pathname: '/charts/treemap',
    icon: 'treemap',
    navigation: true,
  },
  {
    id: 'funnel',
    group: 'Charts',
    job: 'Part of a whole',
    label: 'Funnel',
    title: 'Funnel chart',
    href: '/charts/funnel',
    pathname: '/charts/funnel',
    icon: 'funnel',
    navigation: true,
  },
  {
    id: 'sankey',
    group: 'Charts',
    job: 'Part of a whole',
    label: 'Sankey',
    title: 'Sankey chart',
    href: '/charts/sankey',
    pathname: '/charts/sankey',
    icon: 'sankey',
    navigation: true,
  },
  {
    id: 'stat-cards',
    group: 'Charts',
    job: 'KPIs',
    label: 'Stat cards',
    title: 'Stat cards',
    href: '/charts/stat-cards',
    pathname: '/charts/stat-cards',
    icon: 'sparkline',
    navigation: true,
  },
  {
    id: 'progress',
    group: 'Charts',
    job: 'KPIs',
    label: 'Progress',
    title: 'Progress',
    href: '/charts/progress',
    pathname: '/charts/progress',
    icon: 'progress',
    navigation: true,
  },
  {
    id: 'activity-ring',
    group: 'Charts',
    job: 'KPIs',
    label: 'Activity ring',
    title: 'Activity ring',
    href: '/charts/activity-ring',
    pathname: '/charts/activity-ring',
    icon: 'activity',
    navigation: true,
  },
  {
    id: 'heatmap',
    group: 'Charts',
    job: 'Patterns',
    label: 'Heatmap',
    title: 'Heatmap',
    href: '/charts/heatmap',
    pathname: '/charts/heatmap',
    icon: 'heatmap',
    navigation: true,
  },
  {
    id: 'scatter',
    group: 'Charts',
    job: 'Patterns',
    label: 'Scatter',
    title: 'Scatter chart',
    href: '/charts/scatter',
    pathname: '/charts/scatter',
    icon: 'scatter',
    navigation: true,
  },
  {
    id: 'radar',
    group: 'Charts',
    job: 'Patterns',
    label: 'Radar',
    title: 'Radar chart',
    href: '/charts/radar',
    pathname: '/charts/radar',
    icon: 'radar',
    navigation: true,
  },
  {
    id: 'box-plot',
    group: 'Charts',
    job: 'Patterns',
    label: 'Box plot',
    title: 'Box plot',
    href: '/charts/box-plot',
    pathname: '/charts/box-plot',
    icon: 'boxplot',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'chord-loom',
    group: 'Charts',
    job: 'Cool',
    label: 'Chord loom',
    title: 'Chord loom',
    href: '/charts/chord-loom',
    pathname: '/charts/chord-loom',
    icon: 'chordloom',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'rank-ribbons',
    group: 'Charts',
    job: 'Cool',
    label: 'Rank ribbons',
    title: 'Rank ribbons',
    href: '/charts/rank-ribbons',
    pathname: '/charts/rank-ribbons',
    icon: 'rankribbons',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'event-helix',
    group: 'Charts',
    job: 'Cool',
    label: 'Event helix',
    title: 'Event helix',
    href: '/charts/event-helix',
    pathname: '/charts/event-helix',
    icon: 'eventhelix',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'contour-islands',
    group: 'Charts',
    job: 'Cool',
    label: 'Contour islands',
    title: 'Contour islands',
    href: '/charts/contour-islands',
    pathname: '/charts/contour-islands',
    icon: 'contourislands',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'parallel-ribbons',
    group: 'Charts',
    job: 'Cool',
    label: 'Parallel ribbons',
    title: 'Parallel ribbons',
    href: '/charts/parallel-ribbons',
    pathname: '/charts/parallel-ribbons',
    icon: 'parallelribbons',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'sunburst-terraces',
    group: 'Charts',
    job: 'Cool',
    label: 'Sunburst terraces',
    title: 'Sunburst terraces',
    href: '/charts/sunburst-terraces',
    pathname: '/charts/sunburst-terraces',
    icon: 'sunburstterraces',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'cluster-constellation',
    group: 'Charts',
    job: 'Cool',
    label: 'Cluster constellation',
    title: 'Cluster constellation',
    href: '/charts/cluster-constellation',
    pathname: '/charts/cluster-constellation',
    icon: 'clusterconstellation',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'ternary-prism',
    group: 'Charts',
    job: 'Cool',
    label: 'Ternary prism',
    title: 'Ternary prism',
    href: '/charts/ternary-prism',
    pathname: '/charts/ternary-prism',
    icon: 'ternaryprism',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'wind-rose',
    group: 'Charts',
    job: 'Cool',
    label: 'Wind rose',
    title: 'Wind rose',
    href: '/charts/wind-rose',
    pathname: '/charts/wind-rose',
    icon: 'windrose',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'marimekko-blocks',
    group: 'Charts',
    job: 'Cool',
    label: 'Marimekko blocks',
    title: 'Marimekko blocks',
    href: '/charts/marimekko-blocks',
    pathname: '/charts/marimekko-blocks',
    icon: 'marimekkoblocks',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'intersection-towers',
    group: 'Charts',
    job: 'Cool',
    label: 'Intersection towers',
    title: 'Intersection towers',
    href: '/charts/intersection-towers',
    pathname: '/charts/intersection-towers',
    icon: 'intersectiontowers',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'horizon-folds',
    group: 'Charts',
    job: 'Cool',
    label: 'Horizon folds',
    title: 'Horizon folds',
    href: '/charts/horizon-folds',
    pathname: '/charts/horizon-folds',
    icon: 'horizonfolds',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'circle-archipelago',
    group: 'Charts',
    job: 'Cool',
    label: 'Circle archipelago',
    title: 'Circle archipelago',
    href: '/charts/circle-archipelago',
    pathname: '/charts/circle-archipelago',
    icon: 'circlearchipelago',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'helix-ribbons',
    group: 'Charts',
    job: 'Cool',
    label: 'Helix ribbons',
    title: 'Helix ribbons',
    href: '/charts/helix-ribbons',
    pathname: '/charts/helix-ribbons',
    icon: 'helixribbons',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'voxel-cloud',
    group: 'Charts',
    job: 'Cool',
    label: 'Voxel cloud',
    title: 'Voxel cloud',
    href: '/charts/voxel-cloud',
    pathname: '/charts/voxel-cloud',
    icon: 'voxelcloud',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'arc-bridges',
    group: 'Charts',
    job: 'Cool',
    label: 'Arc bridges',
    title: 'Arc bridges',
    href: '/charts/arc-bridges',
    pathname: '/charts/arc-bridges',
    icon: 'arcbridges',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'terrain',
    group: 'Charts',
    job: 'Cool',
    label: 'Terrain',
    title: 'Terrain',
    href: '/charts/terrain',
    pathname: '/charts/terrain',
    icon: 'terrain',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'hex-city',
    group: 'Charts',
    job: 'Cool',
    label: 'Hex city',
    title: 'Hex city',
    href: '/charts/hex-city',
    pathname: '/charts/hex-city',
    icon: 'hexcity',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'voxel-waffle',
    group: 'Charts',
    job: 'Cool',
    label: 'Voxel waffle',
    title: 'Voxel waffle',
    href: '/charts/voxel-waffle',
    pathname: '/charts/voxel-waffle',
    icon: 'voxel',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'skyline',
    group: 'Charts',
    job: 'Cool',
    label: 'Skyline',
    title: 'Skyline chart',
    href: '/charts/skyline',
    pathname: '/charts/skyline',
    icon: 'skyline',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'block-city',
    group: 'Charts',
    job: 'Cool',
    label: 'Block city',
    title: 'Block city',
    href: '/charts/block-city',
    pathname: '/charts/block-city',
    icon: 'blockcity',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'ridgeline',
    group: 'Charts',
    job: 'Cool',
    label: 'Ridgeline',
    title: 'Ridgeline chart',
    href: '/charts/ridgeline',
    pathname: '/charts/ridgeline',
    icon: 'ridgeline',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'spiral-year',
    group: 'Charts',
    job: 'Cool',
    label: 'Spiral year',
    title: 'Spiral year',
    href: '/charts/spiral-year',
    pathname: '/charts/spiral-year',
    icon: 'spiral',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'candlestick',
    group: 'Finance',
    label: 'Candlestick',
    title: 'Candlestick chart',
    href: '/finance/candlestick',
    pathname: '/finance/candlestick',
    icon: 'candlestick',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'indicator',
    group: 'Finance',
    label: 'Indicators',
    title: 'Indicator chart',
    href: '/finance/indicator',
    pathname: '/finance/indicator',
    icon: 'indicator',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'price',
    group: 'Finance',
    label: 'Price',
    title: 'Price chart',
    href: '/finance/price',
    pathname: '/finance/price',
    icon: 'price',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'depth',
    group: 'Finance',
    label: 'Depth',
    title: 'Depth chart',
    href: '/finance/depth',
    pathname: '/finance/depth',
    icon: 'depth',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'order-book',
    group: 'Finance',
    label: 'Order book',
    title: 'Order book',
    href: '/finance/order-book',
    pathname: '/finance/order-book',
    icon: 'orderbook',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'portfolio',
    group: 'Finance',
    label: 'Portfolio',
    title: 'Portfolio chart',
    href: '/finance/portfolio',
    pathname: '/finance/portfolio',
    icon: 'portfolio',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'customize-colors',
    group: 'Customize',
    label: 'Colors',
    title: 'Colors',
    href: '/customize/colors',
    pathname: '/customize/colors',
    icon: 'palette',
    navigation: true,
  },
  {
    id: 'customize-surfaces',
    group: 'Customize',
    label: 'Surfaces',
    title: 'Surfaces',
    href: '/customize/surfaces',
    pathname: '/customize/surfaces',
    icon: 'surface',
    navigation: true,
  },
  {
    id: 'customize-backgrounds',
    group: 'Customize',
    label: 'Backgrounds',
    title: 'Backgrounds',
    href: '/customize/backgrounds',
    pathname: '/customize/backgrounds',
    icon: 'background',
    navigation: true,
  },
  {
    id: 'customize-3d',
    group: 'Customize',
    label: '3D',
    title: '3D',
    href: '/customize/3d',
    pathname: '/customize/3d',
    icon: 'cube',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'customize-axes',
    group: 'Customize',
    label: 'Axes',
    title: 'Axes',
    href: '/customize/axes',
    pathname: '/customize/axes',
    icon: 'ruler',
    navigation: true,
  },
  {
    id: 'customize-legends',
    group: 'Customize',
    label: 'Legends',
    title: 'Legends',
    href: '/customize/legends',
    pathname: '/customize/legends',
    icon: 'legend',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'customize-hover',
    group: 'Customize',
    label: 'Hover',
    title: 'Hover',
    href: '/customize/hover',
    pathname: '/customize/hover',
    icon: 'hover',
    navigation: true,
  },
  {
    id: 'customize-numbers',
    group: 'Customize',
    label: 'Numbers',
    title: 'Numbers',
    href: '/customize/numbers',
    pathname: '/customize/numbers',
    icon: 'numbers',
    navigation: true,
  },
  {
    id: 'customize-loading',
    group: 'Customize',
    label: 'Loading',
    title: 'Loading',
    href: '/customize/loading',
    pathname: '/customize/loading',
    icon: 'loading',
    navigation: true,
  },
  {
    id: 'customize-empty',
    group: 'Customize',
    label: 'Empty',
    title: 'Empty',
    href: '/customize/empty',
    pathname: '/customize/empty',
    icon: 'empty',
    navigation: true,
  },
  {
    id: 'feature-sync',
    group: 'Features',
    label: 'Sync hover',
    title: 'Sync hover',
    href: '/features/sync',
    pathname: '/features/sync',
    icon: 'sync',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'feature-pin',
    group: 'Features',
    label: 'Pin',
    title: 'Pin',
    href: '/features/pin',
    pathname: '/features/pin',
    icon: 'pin',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'feature-compare',
    group: 'Features',
    label: 'Compare',
    title: 'Compare',
    href: '/features/compare',
    pathname: '/features/compare',
    icon: 'compare',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'feature-targets',
    group: 'Features',
    label: 'Targets & forecasts',
    title: 'Targets and forecasts',
    href: '/features/targets',
    pathname: '/features/targets',
    icon: 'targets',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'feature-performance',
    group: 'Features',
    label: 'Performance',
    title: 'Performance',
    href: '/features/performance',
    pathname: '/features/performance',
    icon: 'speed',
    navigation: true,
    badge: 'New',
  },
  {
    id: 'api',
    group: 'Reference',
    label: 'API reference',
    title: 'API reference',
    href: '/guides/api',
    pathname: '/guides/api',
    icon: 'api',
    navigation: true,
  },
  {
    id: 'motion',
    group: 'Reference',
    label: 'Motion & accessibility',
    title: 'Motion & accessibility',
    href: '/guides/motion',
    pathname: '/guides/motion',
    icon: 'motion',
    navigation: true,
  },
] as const satisfies readonly AppRoute[];

/** The page a pathname belongs to; a nested page such as an API topic belongs to its parent. */
export function routeFor(pathname: string): AppRoute {
  return (appRoutes.find((route) => route.pathname === pathname) ??
    appRoutes.find((route) => pathname.startsWith(`${route.pathname}/`)) ??
    appRoutes.find((route) => route.id === 'area')!) as AppRoute;
}
